spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recruit_sys
    username: root
    password: x555777hy
    data:
      redis:
        host: localhost
        port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名和下划线的转换

alipay:
  app-id: 9021000132656517
  app-private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC92qCe2srg2hNKNGbtMMgY/a+ReqnQvH6J+aR92+6NzHKsd2Ge25e4tpPsC5uVYrwU3oON8BeVESrhKeZSljttKfP4/PtRkWKrzMKUdEiE9AVvbqLKPJqci92FRnKOmaowSTOL8Qszn/KLIFP/lhhqbejh5uwB/nwhHnxL4ARnxS9ggUW80TOGb2fGoQ2LOQwyiB9xY4D3RY6S2WJDET//CxP7yInBMQQ/kYMsF5juybhhKpbgxcGY0iFCPMkeeLvNA/uJ7EgaapPnUL48LqhUTGMYgAIXTCJ6/A4OP4uC6DFh+/8v6NlNOLEeIpMheEnEZh6vBKle4Ymjp6NJrSQJAgMBAAECggEAZQPMbnlPdO/TT6ouEYnhDZr9LVSswglo8pTHdsfsV7ouUaF7aYDBa2CJuBA9CfDszdXO/Vh/06q8u+0FRW/10pF95D8GoVHPxEVASqjMZSFJOw8MwroYMa8hgGYJUeJk8SghqxXnteImtOvQha8g8o/kVz382NrExQJpdB2Pen49c6pn8P3xb2xamQMMVyKiUP2P6Nz4ZV3hTYkGEYKqTX2bwj85Mm0R22ohcKRe7W/2Niz6oOZOgUjQyKSYEFN+EJfQyYlGvN7RBTzfBVfJJuvxbD4/ad/nEYyjDZivGb9FQWQgMaLavXfZJZBJhMXzMT4wYu4JNt2YL8wcXSP6AQKBgQD86b8jjFbMzdyQcQz0qyYJq5VEoP7S8i31jMJ/PUWLsnAqNGMPe9iPXJx8itmu8rBOz3qLTlcorg7Hw4leG2535Bjo0iErwWbFeuhu4MD+NqqpI5y6rt38dvVbjgJBEiiMm6+u+1ohQ7S4ZqGmawyOlijnZ4MvvQZXMmYUTlkzqQKBgQDAK9idxE767Bkh+SLhZrJPmf5YUnboLV2s4TA31A8DVlc3A1rhaFkdgPoSE7Z3Kg0FvNUkvV+NMDCXZyOXfrRZ/htbEP4pcagJp5xNDOHr9tw8beiNfVCOG7oTjfhVcxhdxuPU0yviVjr98sTPuGgtmOqcil6aCAAtEqaP/FapYQKBgQDzFnxH36jCOw/HqVFpjWMHImtbRl8HRA0WmY+MGslQh1a1yhp4lHHHAZ3LOu4V8F+zsEo5wTeW+w1rxi6vTDB2fb/Pb8DAPKjaINNtVwtIjCSmY3tOF6t38KLNuAXEo35j/3Px/NdZZ6k5IDQ5L2UnW36/REfcR5PjlaZ12AR22QKBgEpP6klAA4a2zBU+IUXmj6eGljuTUBYCjQnwXtQH9fJFbh6A9qDZ2DQ3jvx0kQfNxBFm70lwzcVsUC4MHVBVF+sA/5UcohxmriNlpGSLScYUxR+9JMOqJP9/K1qqeNCaXF7PLYU8T+kLjW5sdb0Zw3d2fashOun3lBHZ930QiHahAoGBAPZC9kTcCqHas75b8b8yxvYDQfokAzJwhY52f5uStkXYl4qM/WtqjCsMHLaIqhe2mXyn/jzHhLkbqu1Us82jNqjB/Aw/Z2G9ceC6wABzVcz3mEnK7ejunnoylaVzrDrOXT3FgC0HDNKNYr1OYKDzOoIShzAduaFi2SHKe9tk1WL3
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg7nVC3EvxeIBQBlesaRuPY92pAxOJPXYkb9ORd6BlLgLYVGMfAtuf76MN/ZtpYw/PemjCjZ+ODgz06SEVRdACM4DbbsSkCCNFWxe+dwhB7wv07rMOweogh7avFSiZFT5E6LcpUGty13T0d7x7r1oYFhgYgJ3O82TgfrEFsgZQcyqiOUepqRVaPSciV7dgdJN2R+idoHPKfJ4TGf9s5oCH22+XkT/VKTEzlFBMkMOXYPvjpz0q+GcpASDc0XDNJvb7DHtyEEKETDpfF+WNzkA11Dwgt7nWOwDq3xJBmqPjQnckXCY2SbXuXsSzSi5mDp+Ao+KLJ5TZxp3kaV63x71VQIDAQAB
  notify-url: http://4tvztg.natappfree.cc/alipay/notify